export enum ActionStatusType {
  'NAVIGATING' = 'NAVIGATING',
  'DOCKED' = 'DOCKED',
  'ANCHORED' = 'ANCHORED',
  'UNAVAILABLE' = 'UNAVAILABLE',
  'UNKNOWN' = 'UNKNOWN'
}

export enum ActionStatusReason {
  'MAINTENANCE' = 'MAINTENANCE',
  'WEATHER' = 'WEATHER',
  'REPRESENTATION' = 'REPRESENTATION',
  'ADMINISTRATION' = 'ADMINISTRATION',
  'MCO_AND_LOGISTICS' = 'MCO_AND_LOGISTICS',
  'HARBOUR_CONTROL' = 'HARBOUR_CONTROL',
  'TECHNICAL' = 'TECHNICAL',
  'PERSONNEL' = 'PERSONNEL',
  'OTHER' = 'OTHER'
}
