export enum ControlMethod {
  'SEA' = 'SEA',
  'AIR' = 'AIR',
  'LAND' = 'LAND'
}

export enum ControlResult {
  'YES' = 'YES',
  'NO' = 'NO',
  'NOT_CONTROLLED' = 'NOT_CONTROLLED',
  'NOT_CONCERNED' = 'NOT_CONCERNED'
}

export enum ControlType {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  GENS_DE_MER = 'GENS_DE_MER',
  SECURITY = 'SECURITY',
  NAVIGATION = 'NAVIGATION',
  SECTOR = 'SECTOR',
  TRANSPORT = 'TRANSPORT',
  LANDING_OBLIGATION = 'LANDING_OBLIGATION',
  FISHING_REPORTING_OBLIGATION = 'FISHING_REPORTING_OBLIGATION',
  TECHNICAL_MEASURE = 'TECHNICAL_MEASURE',
  INN_ACTIVITY = 'INN_ACTIVITY',
  OTHER = 'OTHER'
}
