stages:
  - build
  - pre-analyze
  - analyze
  - pre-deploy
  - deploy
variables:
  #  Configuration spécifique projet
  PROJECT_NAME:
    value: rapportnav-v2
    description: "Nom du projet à déployer"
  PROJECT_VERSION:
    value: 0.0.0.14
    description: "Version du projet à déployer"
  PROJECT_ENV:
    value: "int"
    description: "Environnement cible"
  SERVER_ENV:
    value: "int-rapportnav-appli01"
    description: "Serveur cible"
  TAG_LATEST: $NEXUS_DOCKER_REPO/$PROJECT_NAME:latest
  TAG_VERSION: $NEXUS_DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION
  ID_PROJET_INVENTAIRE: 156
  PROJECT_PORTS:
    value: "[80:80]"
    description: "Tableau contenant les ports exposés par le container Docker du projet"
  PROJECT_VOLUMES:
    value: "[]"
    description: "Tableau contenant les volumes du container Docker du projet"
  FAIL_SONAR_CONDITION:
    value: "-Dsonar.qualitygate.wait=true"
    description: "Détermine la commande à passer au scanner Sonar pour bloquer ou non le job. -Dsonar.qualitygate.wait=true fait échouer le job si le quality gate Sonar n'est pas conforme."
  FAIL_TRIVY_CONDITION:
    value: "--severity CRITICAL"
    description: "Détermine la commande à passer à Trivy pour bloquer ou non le job. --severity CRITICAL fait échouer le job si Trivy remonte des anomalies critiques."
include:
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/verif_image_checksum.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/build_projet_maven.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/build_projet_npm.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/construction_image.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/dependency-check.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/analyse_sonar.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/analyse_trivy.yml'
  - project: 'num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2-jobs-scripts'
    ref: master
    file: '/jobs/deploiement_image.yml'
