stages:
  - build
  - pre-analyze
  - analyze
  - pre-deploy-int
  - deploy-int
  - pre-deploy-prod
  - deploy-prod
variables:
  #  Configuration spécifique projet
  PROJECT_NAME:
    value: rapportnav-v2
    description: "Nom du projet à déployer"
  BDD_IAMGE:
    value: postgres:15.5-alpine
    description: "Image de la base de données"
  PROJECT_VERSION:
    value: "0.0.1-alpha.15"
    description: "Version du projet à déployer"
  SERVER_ENV_INT:
    value: "int-rapportnav-appli01"
    description: "Serveur cible d'intégration"
  SERVER_ENV_PROD:
    value: "prod-rapportnav-appli01"
    description: "Serveur cible de production"
  TAG_LATEST: $NEXUS_DOCKER_REPO/$PROJECT_NAME:int
  TAG_VERSION: $NEXUS_DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION
  FAIL_SONAR_CONDITION:
    value: "-Dsonar.qualitygate.wait=true"
    description: "Détermine la commande à passer au scanner Sonar pour bloquer ou non le job. -Dsonar.qualitygate.wait=true fait échouer le job si le quality gate Sonar n'est pas conforme."
  FAIL_TRIVY_CONDITION:
    value: "--severity CRITICAL"
    description: "Détermine la commande à passer à Trivy pour bloquer ou non le job. --severity CRITICAL fait échouer le job si Trivy remonte des anomalies critiques."

include:
  - "/ci/jobs/verif_image_checksum.yml"
  - "/ci/jobs/build_projet_gradle.yml"
  - "/ci/jobs/build_projet_npm.yml"
  - "/ci/jobs/construction_image.yml"
  - "/ci/jobs/dependency-check.yml"
  - "/ci/jobs/analyse_sonar.yml"
  - "/ci/jobs/analyse_trivy.yml"
  - "/ci/jobs/deploiement_image_int.yml"
  - "/ci/jobs/deploiement_image_prod.yml"
