stages:
  - build
  - analyze
  - pre-deploy-int
  - deploy-int
  - tag-image-prod
  - pre-deploy-prod
  - deploy-prod
variables:
  #  Configuration spécifique projet
  PROJECT_NAME:
    value: rapportnav-v2
    description: "Nom du projet à déployer"
  BDD_IAMGE:
    value: postgres:15.5-alpine
    description: "Image de la base de données"
  PROJECT_VERSION:
    value: "1.1.0"
    description: "Version du projet à déployer"
  SERVER_ENV_INT:
    value: "int-rapportnav-appli01"
    description: "Serveur cible d'intégration"
  SERVER_ENV_PROD:
    value: "prod-rapportnav-appli01"
    description: "Serveur cible de production"
  PROXY_HOST: "172.27.229.197"
  PROXY_PORT: "8090"
  TAG_VERSION: $NEXUS_DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION

  #Anlayse Trivy
  FAIL_TRIVY_CONDITION:
    value: "--severity CRITICAL"
    description: "Détermine la commande à passer à Trivy pour bloquer ou non le job. --severity CRITICAL fait échouer le job si Trivy remonte des anomalies critiques."

  #Analyse Sonar
  FAIL_SONAR_CONDITION:
    value: "-Dsonar.qualitygate.wait=true"
    description: "Détermine la commande à passer au scanner Sonar pour bloquer ou non le job. -Dsonar.qualitygate.wait=true fait échouer le job si le quality gate Sonar n'est pas conforme."

  #Analyse Dependency-check
  FAIL_DP_CHECK_LVL:
    value: "8"
    description: "Niveau de la criticité limite de l'analyse Dependency-Check"

include:
  - "/jobs-build-CI/build_projet_gradle.yml"
  - "/jobs-build-CI/build_projet_npm.yml"
  - "/jobs-build-CI/construction_image.yml"
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/analyse_trivy.yml'
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/analyse_sonar.yml'
  - "/jobs-build-CI/analyse_dependency-check.yml"
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/deploiement_image_int.yml'
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/deploiement_image_prod.yml'

