version: "3"
services:
  app:
    build:
      context: .
      dockerfile: infra/docker/app/DockerfileDev
      target: build-all
    ports:
      - "80:80"
    volumes:
      - ./frontend:/tmp/frontend
    depends_on:
      - db
      - metabase
    # networks:
    #   - backend-network

  db:
    image: postgres:15.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapportnavdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30
    # networks:
    #   - backend-network

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      # - MB_DB_CONNECTION_URI="db:5432/rapportnavdb?user=postgres&password=postgres"
      - MB_DB_CONNECTION_URI=postgres://db:5432/rapportnavdb?currentSchema=metabase
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      # - MB_DB_DBNAME=rapportnavdb
      # - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      # - MB_DB_HOST=db
    restart: always
    depends_on:
      - db
  # networks:
  #   - backend-network

# networks:
#   backend-network:
#     external: false
#     name: backend-network
#   default:
#     driver: bridge

volumes:
  db_data:
    name: db
  metabase_data:
