version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: build-all
    ports:
      - ${BACKEND_HTTP_PORT}:8880
      - 8000:8000
    volumes:
      - ./frontend:/tmp/frontend
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapportnavdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30
