name: 'Frontend Build'
description: 'Install and build frontend'
version: 'v1.0.0'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: ./frontend/package-lock.json
        node-version: 24

    - name: Install npm dependencies
      shell: bash
      run: make front-ci

    - name: Build Frontend
      shell: bash
      run: make front-build

