name: 'Frontend Build'
description: 'Install and build frontend'
version: 'v1.0.0'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Setup Node.js environment
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        cache: npm
        cache-dependency-path: ./frontend/package-lock.json
        node-version: 24

    - name: Install npm dependencies
      shell: bash
      run: make front-ci

    - name: Build Frontend
      shell: bash
      run: make front-build

