version: "3"
services:
  db:
    image: postgres:15.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapportnavdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30

  backend:
    build:
      context: ..
      dockerfile: ./infra/docker/app/DockerfileDev.old
      target: run-backend
    ports:
      - 80:80
      - 8880:8880
    volumes:
      - ./backend:/tmp/backend
    depends_on:
      - db
      - metabase

  frontend:
    build:
      context: ..
      dockerfile: ./infra/docker/app/DockerfileDev.old
      target: run-frontend
    ports:
      - 5173:5173
      # - 3000:3000
    volumes:
      - ./frontend:/tmp/frontend

  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    volumes:
      - metabase_data:/metabase-data
    environment:
      - MB_DB_CONNECTION_URI=postgres://db:5432/rapportnavdb?currentSchema=metabase
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
    restart: always
    depends_on:
      - db

volumes:
  db_data:
    name: db
  metabase_data:
