version: '3.8'
name: rapportnav2
services:
  backend:
    build:
      context: ..
      dockerfile: ./infra/docker/app/DockerfileLocalBack
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ../backend:/tmp/backend
      - ../infra/configurations/backend:/tmp/backend/configurations
    environment:
      - VERSION=NO_VERSION
      - ENV_PROFILE=local
      - ENV_DB_URL=jdbc:postgresql://db:5432/rapportnavdb?user=postgres&password=postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/app/DockerfileLocalFront
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/tmp/frontend

  db:
    image: postgres:15.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapportnavdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    environment:
      - CUSTOM_PORT=8001
      - CUSTOM_HTTPS_PORT=8001
      #      - PUID=1000  # Set the user id
      #      - PGID=1000  # Set the group id
      - TZ=Europe/Paris  # Set the timezone
    ports:
      - "8100:8100"
    command: /usr/bin/libreoffice --headless --accept="socket,host=0.0.0.0,port=8100;urp;StarOffice.ServiceManager" --norestore --nofirststartwizard

volumes:
  db:
    name: rapportnavdb
#  metabase_data:
