ROLLBACK;

DO $$
  DECLARE
    my_rec RECORD;
    action_insert_count integer := 0;
    my_action_curs CURSOR FOR
      SELECT m_action.*
      FROM (
             SELECT
               id,
               mission_id,
               'ANTI_POLLUTION'::"ActionType" AS action_type,
               start_datetime_utc,
               end_datetime_utc,
               observations,
               is_complete_for_stats,
               latitude,
               longitude,
               detected_pollution,
               pollution_observed_by_authorized_agent,
               diversion_carried_out,
               simple_brewing_operation,
               anti_pol_device_deployed,
               null as control_method,
               null as vessel_identifier,
               null as vessel_type,
               null as vessel_size,
               null as identity_controlled_person,
               null::integer as nb_of_intercepted_vessels,
               null::integer as nb_of_intercepted_migrants,
               null::integer as nb_of_suspected_smugglers,
               null::boolean as is_vessel_rescue,
               null::boolean as is_person_rescue,
               null::boolean as is_vessel_noticed,
               null::boolean as is_vessel_towed,
               null::boolean as is_in_srr_or_followed_by_cross_mrcc,
               null::integer as number_persons_rescued,
               null::integer as number_of_deaths,
               null::boolean as operation_follows_defrep,
               null as location_description,
               null::boolean as is_migration_rescue,
               null::integer as nb_vessels_tracked_without_intervention,
               null::integer as nb_assisted_vessels_returning_to_shore,
               null as status,
               null as reason,
               null::uuid as owner_id,
               null::integer as nbr_of_hours
             FROM mission_action_anti_pollution
             UNION ALL SELECT
                         id,
                         mission_id,
                         'BAAEM_PERMANENCE'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_baaem_permanence
             UNION ALL SELECT
                         id,
                         mission_id,
                         'CONTROL'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         latitude,
                         longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         vessel_identifier,
                         vessel_type,
                         vessel_size,
                         identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_control
             UNION ALL SELECT
                         id,
                         mission_id,
                         'NOTE'::"ActionType" AS action_type,
                         start_datetime_utc,
                         null as end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         NULL as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_free_note
             UNION ALL SELECT
                         id,
                         mission_id,
                         'ILLEGAL_IMMIGRATION'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         latitude,
                         longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         nb_of_intercepted_vessels,
                         nb_of_intercepted_migrants,
                         nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_illegal_immigration
             UNION ALL SELECT
                         id,
                         mission_id,
                         'ILLEGAL_IMMIGRATION'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         latitude,
                         longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         is_vessel_rescue,
                         is_person_rescue,
                         is_vessel_noticed,
                         is_vessel_towed,
                         is_in_srr_or_followed_by_cross_mrcc,
                         number_persons_rescued,
                         number_of_deaths,
                         operation_follows_defrep,
                         location_description,
                         is_migration_rescue,
                         nb_vessels_tracked_without_intervention,
                         nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_rescue
             UNION ALL SELECT
                         id,
                         mission_id,
                         'NAUTICAL_EVENT'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_nautical_event
             UNION ALL SELECT
                         id,
                         mission_id,
                         'PUBLIC_ORDER'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_public_order
             UNION ALL SELECT
                         id,
                         mission_id,
                         'REPRESENTATION'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_representation
             UNION ALL SELECT
                         id,
                         mission_id,
                         'STATUS'::"ActionType" AS action_type,
                         start_datetime_utc,
                         null as end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         status,
                         reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_status
             UNION ALL SELECT
                         id,
                         mission_id,
                         'VIGIMER'::"ActionType" AS action_type,
                         start_datetime_utc,
                         end_datetime_utc,
                         observations,
                         is_complete_for_stats,
                         null as latitude,
                         null as longitude,
                         null as detected_pollution,
                         null as pollution_observed_by_authorized_agent,
                         null as diversion_carried_out,
                         null as simple_brewing_operation,
                         null as anti_pol_device_deployed,
                         null as control_method,
                         null as vessel_identifier,
                         null as vessel_type,
                         null as vessel_size,
                         null as identity_controlled_person,
                         null::integer as nb_of_intercepted_vessels,
                         null::integer as nb_of_intercepted_migrants,
                         null::integer as nb_of_suspected_smugglers,
                         null::boolean as is_vessel_rescue,
                         null::boolean as is_person_rescue,
                         null::boolean as is_vessel_noticed,
                         null::boolean as is_vessel_towed,
                         null::boolean as is_in_srr_or_followed_by_cross_mrcc,
                         null::integer as number_persons_rescued,
                         null::integer as number_of_deaths,
                         null::boolean as operation_follows_defrep,
                         null as location_description,
                         null::boolean as is_migration_rescue,
                         null::integer as nb_vessels_tracked_without_intervention,
                         null::integer as nb_assisted_vessels_returning_to_shore,
                         null as status,
                         null as reason,
                         null::uuid as owner_id,
                         null::integer as nbr_of_hours
             FROM mission_action_vigimer
           ) m_action;

  BEGIN
    OPEN my_action_curs;
    LOOP
      FETCH my_action_curs INTO my_rec;
      EXIT WHEN NOT FOUND;

      RAISE NOTICE 'Processing action_id: %', my_rec.id;

      -- TARGET LOGIC
      IF NOT EXISTS (
        SELECT 1 FROM mission_action WHERE id = my_rec.id
      ) THEN
        -- Insert new entry in mission_action
        RAISE NOTICE ' Insert new mission action action_id: %', my_rec.id;
        INSERT INTO mission_action (
          id,
          mission_id,
          action_type,
          start_datetime_utc,
          end_datetime_utc,
          observations,
          is_complete_for_stats,
          latitude,
          longitude,
          detected_pollution,
          pollution_observed_by_authorized_agent,
          diversion_carried_out,
          simple_brewing_operation,
          anti_pol_device_deployed,
          control_method,
          vessel_identifier,
          vessel_type,
          vessel_size,
          identity_controlled_person,
          nb_of_intercepted_vessels,
          nb_of_intercepted_migrants,
          nb_of_suspected_smugglers,
          is_vessel_rescue,
          is_person_rescue,
          is_vessel_noticed,
          is_vessel_towed,
          is_in_srr_or_followed_by_cross_mrcc,
          number_persons_rescued,
          number_of_deaths,
          operation_follows_defrep,
          location_description,
          is_migration_rescue,
          nb_vessels_tracked_without_intervention,
          nb_assisted_vessels_returning_to_shore,
          status,
          reason,
          owner_id,
          nbr_of_hours
        )
        VALUES (
                 my_rec.id,
                 my_rec.mission_id,
                 my_rec.action_type,
                 my_rec.start_datetime_utc,
                 my_rec.end_datetime_utc,
                 my_rec.observations,
                 my_rec.is_complete_for_stats,
                 my_rec.latitude,
                 my_rec.longitude,
                 my_rec.detected_pollution,
                 my_rec.pollution_observed_by_authorized_agent,
                 my_rec.diversion_carried_out,
                 my_rec.simple_brewing_operation,
                 my_rec.anti_pol_device_deployed,
                 my_rec.control_method,
                 my_rec.vessel_identifier,
                 my_rec.vessel_type,
                 my_rec.vessel_size,
                 my_rec.identity_controlled_person,
                 my_rec.nb_of_intercepted_vessels,
                 my_rec.nb_of_intercepted_migrants,
                 my_rec.nb_of_suspected_smugglers,
                 my_rec.is_vessel_rescue,
                 my_rec.is_person_rescue,
                 my_rec.is_vessel_noticed,
                 my_rec.is_vessel_towed,
                 my_rec.is_in_srr_or_followed_by_cross_mrcc,
                 my_rec.number_persons_rescued,
                 my_rec.number_of_deaths,
                 my_rec.operation_follows_defrep,
                 my_rec.location_description,
                 my_rec.is_migration_rescue,
                 my_rec.nb_vessels_tracked_without_intervention,
                 my_rec.nb_assisted_vessels_returning_to_shore,
                 my_rec.status,
                 my_rec.reason,
                 my_rec.owner_id,
                 my_rec.nbr_of_hours
               );
        action_insert_count := action_insert_count + 1;
      END IF;

    END LOOP;
    CLOSE my_action_curs;

    RAISE NOTICE 'Inserted % rows into mission_action', action_insert_count;
  END
$$;
