DO
$$
BEGIN
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_SECTOR_FISHING';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_SECTOR_PLAISANCE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_ROADSIDE';
END $$;
