DO
$$
BEGIN
ALTER TABLE sati ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE sati ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sati ADD COLUMN IF NOT EXISTS updated_by INTEGER NULL;
ALTER TABLE sati ADD COLUMN IF NOT EXISTS mission_id INTEGER NULL;
END
$$;
