DO
$$
BEGIN
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'SECTOR';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'TRANSPORT';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'LANDING_OBLIGATION';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'FISHING_REPORTING_OBLIGATION';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'TECHNICAL_MEASURE';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'INN_ACTIVITY';
ALTER TYPE "ControlType" ADD VALUE IF NOT EXISTS 'OTHER';
END
$$;
