DO
$$
BEGIN
ALTER TABLE agent_role ADD COLUMN IF NOT EXISTS priority INTEGER NULL;
ALTER TABLE agent_role ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE service ADD COLUMN IF NOT EXISTS  deleted_at TIMESTAMP;
END
$$;
