DO $$
BEGIN
    INSERT INTO agent (first_name, last_name) VALUES
                                    -- jeanne barret B:
                                    ('Christian', 'Sauvage'),
                                    ('François', 'Dambron'),
                                    ('Frédéric', 'Grégoire'),
                                    ('Nicolas', 'Delattre'),
                                    ('Jean François', 'Albert'),
                                    ('Guillaume', 'Gatoux'),
                                    ('Arnaud', 'Celton'),
                                    ('Francis', 'Beyaert'),
                                    ('Gaylord', 'Suret'),
                                    ('Thierry', 'Lesaulnier'),
                                    ('Laurent', 'Duval'),
                                    ('Philippe', 'Bon'),
                                    ('Adeline', 'Lagadec'),
                                    ('Pascal', 'Morel'),
                                    ('Yann', 'Mollat'),
                                    -- iris A:
                                    ('Xavier', 'Lacourrege'),
                                    ('Thierry', 'Crochard'),
                                    ('Marc', 'Ottini'),
                                    ('Gilles', 'Menuge'),
                                    ('Jean-David', 'Duhaudt'),
                                    ('Stephane', 'Bistour'),
                                    ('Herve', 'Simon'),
                                    ('Fabien', 'Roman'),
                                    ('Stéphane', 'Lelièvre'),
                                    ('Yves', 'Maniette'),
                                    ('Gaétan', 'Merrien'),
                                    ('Frédéric', 'Beyaert'),
                                    ('Franck', 'Touron'),
                                    ('Frédéric', 'Dechaine'),
                                    ('Francois', 'Le Bon'),
                                    -- themis A:
                                    ('Ariane', 'Regaud'),
                                    ('Philippe', 'Gahinet'),
                                    ('Didier', 'Cozic'),
                                    ('Régis', 'Soubise'),
                                    ('Philippe', 'Davies'),
                                    ('Franck', 'Grouiec'),
                                    ('Stéphane', 'Hellio'),
                                    ('Pascal', 'Rousselet'),
                                    ('Laurent', 'Forgeard'),
                                    ('Oswald', 'Isore'),
                                    ('Yvan', 'Pavie'),
                                    ('Thierry', 'Yhuel'),
                                    ('Stéphane', 'Horel'),
                                    ('Pascal', 'Barinka'),
                                    ('Nicolas', 'Daden'),
                                    ('Cyril', 'Le Scoarnec'),
                                    -- themis B:
                                    ('Frédéric', 'Schneider'),
                                    ('Pascal', 'Isore'),
                                    ('Philippe', 'Fournier'),
                                    ('Régis', 'Tertu'),
                                    ('Raymond', 'Cacitti'),
                                    ('Philippe', 'Darsu'),
                                    ('Michel', 'Marchand'),
                                    ('Cyril', 'Lelandois'),
                                    ('Jean Marc', 'Bourbigot'),
                                    ('David', 'Collomp'),
                                    ('Jérome', 'Fievet'),
                                    ('Brian', 'O’Rorke'),
                                    ('Ludovic', 'Daoulas'),
                                    ('Loup', 'Genty'),
                                    ('JL', 'Chapovaloff'),
                                    -- gyptis A:
                                   ('Ludovic', 'Bouteillon'),
                                   ('Serge', 'Croville'),
                                   ('Sylvain', 'Rebeyrotte'),
                                   ('Thomas', 'Le Gall'),
                                   ('Lilian', 'Roue'),
                                   ('Laurent', 'Paronneau'),
                                   ('Nicolas', 'Peyre'),
                                   ('José', 'Maillot'),
                                   ('Michel', 'Ceres'),
                                   ('David', 'Demilly'),
                                   ('Anne', 'Zamaron'),
                                   ('Cyrille', 'Carval'),
                                   ('Guillaume', 'Mardelle'),
                                   ('Pierre', 'Buriez');

END $$;