DO
$$
  BEGIN
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONDUCT_HEARING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'COMMUNICATION';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TRAINING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'UNIT_MANAGEMENT_PLANNING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'UNIT_MANAGEMENT_TRAINING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_SECTOR';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_NAUTICAL_LEISURE';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CONTROL_SLEEPING_FISHING_GEAR';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'OTHER_CONTROL';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'RESOURCES_MAINTENANCE';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'MEETING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PV_DRAFTING';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'HEARING_CONDUCT';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'LAND_SURVEILLANCE';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'FISHING_SURVEILLANCE';
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS training_type VARCHAR(32) NULL;
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS is_within_department BOOLEAN NULL;
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS has_diving_during_operation BOOLEAN NULL;
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS unit_management_training_type VARCHAR(32) NULL;
  END
$$;
