

DROP TABLE IF EXISTS sati_inspector CASCADE;
DROP TABLE IF EXISTS sati CASCADE;
DROP TABLE IF EXISTS sati_vessel CASCADE;
DROP TABLE IF EXISTS sati_party CASCADE;
DROP TABLE IF EXISTS contact CASCADE;
DROP TABLE IF EXISTS address CASCADE;


CREATE TABLE sati
(
  id          UUID PRIMARY KEY      DEFAULT gen_random_uuid(),
  module      VARCHAR(50)  NOT NULL,
  action_id   VARCHAR(255) NOT NULL UNIQUE,
  resource_id INTEGER,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


CREATE TABLE sati_vessel
(
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sati_id         UUID        NOT NULL REFERENCES sati (id) ON DELETE CASCADE,
  pno_type        VARCHAR(50),
  trip_number     VARCHAR(50),
  is_master_owner BOOLEAN     NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE sati_inspector
(
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sati_id        UUID        NOT NULL REFERENCES sati (id) ON DELETE CASCADE,
  authority_type VARCHAR(50),
  agent_id       INTEGER,
  is_out_of_unit BOOLEAN     NOT NULL DEFAULT false,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE sati_party
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_type   VARCHAR(50),
  vessel_id    INTEGER REFERENCES sati_vessel (id) ON DELETE CASCADE,
  inspector_id INTEGER REFERENCES sati_inspector (id) ON DELETE CASCADE,
  comments     TEXT,
  signature    BOOLEAN     NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ          DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Child of sati_party: FK on child side
CREATE TABLE contact
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id    INTEGER REFERENCES sati_party (id) ON DELETE CASCADE,
  full_name   VARCHAR(255),
  first_name  VARCHAR(255),
  last_name   VARCHAR(255),
  nationality VARCHAR(16),
  email       VARCHAR(255),
  phone       VARCHAR(50),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Child of contact: FK on child side
CREATE TABLE address
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id   INTEGER REFERENCES contact (id) ON DELETE CASCADE,
  street       VARCHAR(255),
  full_address VARCHAR(400),
  zipcode      VARCHAR(20),
  town         VARCHAR(100),
  country      VARCHAR(3),
  longitude    DOUBLE PRECISION,
  latitude     DOUBLE PRECISION,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sati_vessel_sati_id ON sati_vessel (sati_id);
CREATE INDEX IF NOT EXISTS idx_sati_inspector_sati_id ON sati_inspector (sati_id);
CREATE INDEX IF NOT EXISTS idx_sati_party_vessel_id ON sati_party (vessel_id);
CREATE INDEX IF NOT EXISTS idx_sati_party_inspector_id ON sati_party (inspector_id);
CREATE INDEX IF NOT EXISTS idx_contact_party_id ON contact (party_id);
CREATE INDEX IF NOT EXISTS idx_address_contact_id ON address (contact_id);
