DO
$$
  BEGIN
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'UNIT_MANAGEMENT_OTHER';
    ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'MARITIME_SURVEILLANCE';
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS resource_type VARCHAR(32) NULL;
    ALTER TABLE mission_action ADD COLUMN IF NOT EXISTS resource_id INTEGER NULL;
  END
$$;
