
DROP TABLE IF EXISTS sati_inspector;
DROP TABLE IF EXISTS sati;
DROP TABLE IF EXISTS sati_vessel;
DROP TABLE IF EXISTS sati_party;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS address;

CREATE TABLE address
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  street       VARCHAR(255),
  full_address VARCHAR(400),
  zipcode      VARCHAR(20),
  town         VARCHAR(100),
  country      VARCHAR(16),
  longitude    DOUBLE PRECISION,
  latitude     DOUBLE PRECISION,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contact
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR(255),
  first_name  VARCHAR(255),
  last_name   VARCHAR(255),
  nationality VARCHAR(16),
  email       VARCHAR(255),
  phone       VARCHAR(50),
  address_id  INTEGER REFERENCES address (id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sati_party
(
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_type VARCHAR(50),
  comments   TEXT,
  signature  BOOLEAN NOT NULL DEFAULT false,
  contact_id INTEGER REFERENCES contact (id),
  created_at TIMESTAMPTZ      DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sati_vessel
(
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pno_type        VARCHAR(50),
  trip_number     VARCHAR(50),
  agent_id        INTEGER REFERENCES sati_party (id),
  master_id       INTEGER REFERENCES sati_party (id),
  is_master_owner BOOLEAN     NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE sati
(
  id          UUID PRIMARY KEY      DEFAULT gen_random_uuid(),
  module      VARCHAR(50)  NOT NULL,
  action_id   VARCHAR(255) NOT NULL UNIQUE,
  resource_id INTEGER,
  vessel_id   INTEGER REFERENCES sati_vessel (id),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


CREATE TABLE sati_inspector
(
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sati_id        UUID        NOT NULL REFERENCES sati (id) ON DELETE CASCADE,
  party_id       INTEGER REFERENCES sati_party (id),
  authority_type VARCHAR(50),
  agent_id       INTEGER,
  is_out_of_unit BOOLEAN     NOT NULL DEFAULT false,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_contact_address_id ON contact (address_id);
CREATE INDEX IF NOT EXISTS idx_sati_party_contact_id ON sati_party (contact_id);
CREATE INDEX IF NOT EXISTS idx_sati_vessel_agent_id ON sati_vessel (agent_id);
CREATE INDEX IF NOT EXISTS idx_sati_vessel_master_id ON sati_vessel (master_id);
CREATE INDEX IF NOT EXISTS idx_sati_vessel_id ON sati (vessel_id);
CREATE INDEX IF NOT EXISTS idx_sati_inspector_sati_id ON sati_inspector (sati_id);
CREATE INDEX IF NOT EXISTS idx_sati_inspector_party_id ON sati_inspector (party_id);
