package fr.gouv.dgampa.rapportnav.infrastructure.api.bff.model.v2.sati

import java.time.Instant
import java.util.UUID

data class Sati(
    val id: UUID? = null,
    val module: String,
    val actionId: String,
    val createdAt: Instant? = null,
    val updatedAt: Instant? = null,
    val actionTaken: String? = null,
    val agentContact: Contact? = null,
    val appointingAuthority: String? = null,
    val beneficialOwnerContact: Contact? = null,
    val catchCertificateInfo: Boolean? = null,
    val chartererContact: Contact? = null,
    val commonMarketingStandards: Boolean? = null,
    val driverContact: Contact? = null,
    val euFishingTripId: String? = null,
    val fisheryLotLabelling: Boolean? = null,
    val fisheryProductDocumentsInspection: Boolean? = null,
    val fisheryProductStorageMechanismInspected: Boolean? = null,
    val fisheryProductWeighedBeforeSale: Boolean? = null,
    val freshnessCategories: String? = null,
    val importerContact: Contact? = null,
    val infringementsObservations: String? = null,
    val inspectionEndDatetimeUtc: Instant? = null,
    val inspectionStartDatetimeUtc: Instant,
    val inspectionLocationAddressId: String? = null,
    val inspectorComments: String? = null,
    val inspectorNameOrId: String? = null,
    val inspectorSignature: Boolean? = null,
    val inspectorUniqueId: String? = null,
    val landingDeclarationInfo: Boolean? = null,
    val lotIdSpeciesQuantities: String? = null,
    val lotsArt58Compliance: Boolean? = null,
    val marketOwnerContact: Contact? = null,
    val marketOwnerRepresentativeContact: Contact? = null,
    val marketPremisesAddressId: String? = null,
    val marketPremisesLocation: String? = null,
    val marketPremisesName: String? = null,
    val masterComments: String? = null,
    val masterContact: Contact? = null,
    val newLotCompositionInfo: String? = null,
    val operatorComments: String? = null,
    val operatorSignature: Boolean? = null,
    val patrolVesselExternalMarking: String? = null,
    val patrolVesselRadioCallSign: String? = null,
    val registeredBuyerContact: Contact? = null,
    val responsiblePersonSignature: Boolean? = null,
    val sizeGradingCategories: String? = null,
    val supplierInvoiceInfo: Boolean? = null,
    val takeOverDeclarationInfo: Boolean? = null,
    val traceabilityRecordingSystemArt58: Boolean? = null,
    val traceabilitySupplierIdentificationSystem: Boolean? = null,
    val tractorRegistrationNumber: String? = null,
    val trailerRegistrationNumber: String? = null,
    val transportDocumentInfo: Boolean? = null,
    val transporterComments: String? = null,
    val transporterSignature: Boolean? = null,
    val useOfUndersizedFisheryProducts: Boolean? = null,
    val vehicleCountryCode: String? = null,
    val vehicleOwnerContact: Contact? = null,
    val vehicleType: String? = null,
    val vesselOwnerContact: Contact? = null
)
