package fr.gouv.dgampa.rapportnav.infrastructure.api.bff.model.v2.sati

import java.time.OffsetDateTime
import java.util.UUID

data class SatiResponse(
    val id: UUID? = null,
    val module: String,
    val ownerId: UUID,
    val createdAt: OffsetDateTime? = null,
    val updatedAt: OffsetDateTime? = null,
    val actionTaken: String? = null,
    val agentContact: ContactResponse? = null,
    val appointingAuthority: String? = null,
    val beneficialOwnerContact: ContactResponse? = null,
    val catchCertificateInfo: Boolean? = null,
    val chartererContact: ContactResponse? = null,
    val commonMarketingStandards: Boolean? = null,
    val driverContact: ContactResponse? = null,
    val euFishingTripId: String? = null,
    val fisheryLotLabelling: Boolean? = null,
    val fisheryProductDocumentsInspection: Boolean? = null,
    val fisheryProductStorageMechanismInspected: Boolean? = null,
    val fisheryProductWeighedBeforeSale: Boolean? = null,
    val freshnessCategories: String? = null,
    val importerContact: ContactResponse? = null,
    val infringementsObservations: String? = null,
    val inspectionEndDatetimeUtc: OffsetDateTime? = null,
    val inspectionStartDatetimeUtc: OffsetDateTime,
    val inspectionLocationAddressId: UUID? = null,
    val inspectorComments: String? = null,
    val inspectorNameOrId: String? = null,
    val inspectorSignature: Boolean? = null,
    val inspectorUniqueId: String? = null,
    val landingDeclarationInfo: Boolean? = null,
    val lotIdSpeciesQuantities: String? = null,
    val lotsArt58Compliance: Boolean? = null,
    val marketOwnerContact: ContactResponse? = null,
    val marketOwnerRepresentativeContact: ContactResponse? = null,
    val marketPremisesAddressId: UUID? = null,
    val marketPremisesLocation: String? = null,
    val marketPremisesName: String? = null,
    val masterComments: String? = null,
    val masterContact: ContactResponse? = null,
    val newLotCompositionInfo: String? = null,
    val operatorComments: String? = null,
    val operatorSignature: Boolean? = null,
    val patrolVesselExternalMarking: String? = null,
    val patrolVesselRadioCallSign: String? = null,
    val registeredBuyerContact: ContactResponse? = null,
    val responsiblePersonSignature: Boolean? = null,
    val sizeGradingCategories: String? = null,
    val supplierInvoiceInfo: Boolean? = null,
    val takeOverDeclarationInfo: Boolean? = null,
    val traceabilityRecordingSystemArt58: Boolean? = null,
    val traceabilitySupplierIdentificationSystem: Boolean? = null,
    val tractorRegistrationNumber: String? = null,
    val trailerRegistrationNumber: String? = null,
    val transportDocumentInfo: Boolean? = null,
    val transporterComments: String? = null,
    val transporterSignature: Boolean? = null,
    val useOfUndersizedFisheryProducts: Boolean? = null,
    val vehicleNationality: String? = null,
    val vehicleOwnerContact: ContactResponse? = null,
    val vehicleType: String? = null,
    val vesselOwnerContact: ContactResponse? = null
)
