package fr.gouv.dgampa.rapportnav.domain.entities.mission.fish.fishActions

import com.neovisionaries.i18n.CountryCode
import fr.gouv.dgampa.rapportnav.domain.entities.mission.fish.ControlUnit
import java.time.Instant


typealias FishAction = MissionAction

data class MissionAction(
    val id: Int? = null,
    val missionId: Int,
    val vesselId: Int? = null,
    val vesselName: String? = null,
    val internalReferenceNumber: String? = null,
    val externalReferenceNumber: String? = null,
    val ircs: String? = null,
    val flagState: CountryCode? = null,
    val districtCode: String? = null,
    val faoAreas: List<String> = listOf(),
    val actionType: MissionActionType,
    val actionDatetimeUtc: Instant,
    val actionEndDatetimeUtc: Instant? = null,
    val emitsVms: ControlCheck? = null,
    val emitsAis: ControlCheck? = null,
    val vmsEmissionControlBeforeArrival: ControlCheck? = null,
    val portEntranceAndLandingAuthorized: ControlCheck? = null,
    val logbookFilledPriorToControl: ControlCheck? = null,
    val flightGoals: List<FlightGoal> = listOf(),
    val logbookMatchesActivity: ControlCheck? = null,
    val licencesMatchActivity: ControlCheck? = null,
    val speciesWeightControlled: ControlCheck? = null,
    val speciesSizeControlled: ControlCheck? = null,
    val separateStowageOfPreservedSpecies: ControlCheck? = null,
    val propulsionEnginePowerControl: ControlCheck? = null,
    val fishingLicencesMatchActivity: ControlCheck? = null,
    val stowagePlanPresent: ControlCheck? = null,
    val onboardWeighingPermit: ControlCheck? = null,
    val weighingCertificateAndSystemsValid: ControlCheck? = null,
    val underSizedSeparateStowage: ControlCheck? = null,
    val underSizedSeparateRecording: ControlCheck? = null,
    val minimumConservationReferenceSizeControlled: ControlCheck? = null,
    val cratesWeighingSamplingControl: ControlCheck? = null,
    val approvedWeighingOperatorInformation: ControlCheck? = null,
    val holdControlledAfterUnloading: ControlCheck? = null,
    val catchesWeighedAtLanding: ControlCheck? = null,
    val licencesAndLogbookObservations: String? = null,
    val speciesObservations: String? = null,
    val seizureAndDiversion: Boolean? = null,
    val numberOfVesselsFlownOver: Int? = null,
    val unitWithoutOmegaGauge: Boolean? = null,
    val controlQualityComments: String? = null,
    val userTrigram: String,
    val segments: List<FleetSegment> = listOf(),
    val facade: String? = null,
    val longitude: Double? = null,
    val latitude: Double? = null,
    val portLocode: String? = null,
    // This field is only used when fetching missions
    var portName: String? = null,
    val vesselTargeted: ControlCheck? = null,
    val seizureAndDiversionComments: String? = null,
    val otherComments: String? = null,
    val gearOnboard: List<GearControl> = listOf(),
    val speciesOnboard: List<SpeciesOnboardControl> = listOf(),
    val discardedSpecies: List<DiscardedSpeciesControl> = listOf(),
    val isFromPoseidon: Boolean,
    /**
     * This field is only used by the `GetVesselControls` use-case.
     * /!\ Do not use it to get `controlUnits` as the field will be empty be default.
     */
    var controlUnits: List<ControlUnit> = listOf(),
    val hasSomeGearsSeized: Boolean,
    val hasSomeSpeciesSeized: Boolean,
    val completedBy: String? = null,
    val completion: Completion,
    val isLastHaul: Boolean = false,
    val isAdministrativeControl: Boolean? = null,
    val isComplianceWithWaterRegulationsControl: Boolean? = null,
    val isSafetyEquipmentAndStandardsComplianceControl: Boolean? = null,
    val isSeafarersControl: Boolean? = null,
    val isINNControl: Boolean = false,
    val isGangwayDeployed: Boolean? = null,
    var observationsByUnit: String? = null,
    var speciesQuantitySeized: Int? = null,
    val infractions: List<FishInfraction> = listOf(),
    val hasDivingDuringOperation: Boolean? = null,
    val incidentDuringOperation: Boolean? = null,
    val vesselLength: Double? = null,
    val vesselType: String? = null,
    val imo: String? = null,
    val proprietorName: String? = null,
    val proprietorPhones: List<String>? = listOf(),
    val proprietorEmails: List<String>? = listOf(),
    val proprietorNationality: String? = null,
    val proprietorAddress: String? = null,
    val tripNumber: String? = null,
    val pnoReportId: String? = null,
    val pnoPurpose: LogbookMessagePurpose? = null,
    val lastDeparturePortLocode: String? = null,
    val lastDeparturePortName: String? = null,
    val lastDepartureDateTime: Instant? = null,
    val operatorName: String? = null,
    val operatorPhones: List<String>? = listOf(),
    val operatorEmails: List<String>? = listOf(),
    val operatorNationality: String? = null,
    val operatorAddress: String? = null,
)
