name: 'Backend Build'
description: 'Install and build build'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        distribution: liberica
        java-version: 25

    - name: Print JAVA_HOME
      shell: bash
      run: |
        echo "JAVA_HOME is $JAVA_HOME"
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

    - name: cd backend
      shell: bash
      run: cd backend

    - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      id: setup-gradle
      with:
        gradle-version: wrapper
        dependency-graph: generate-and-submit

    - name: build package
      shell: bash
      run: make back-assemble

    - name: set up LibreOffice
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice

