name: 'Frontend Build'
description: 'Install and build frontend'
version: 'v1.0.0'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install npm dependencies
      shell: bash
      run: make front-ci

    - name: Build Frontend
      shell: bash
      run: make front-build

