---
#------------------------------------------------------------------------
#   Liste des taches d'installation/mise à jour d'une image Docker
#------------------------------------------------------------------------

# Connexion au repository Nexus/récupération de l'image/logout
- name: "Log into nexus repository"
  command: docker login {{ nexus_repo }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true

- name: "Pull docker images"
  command: "docker pull {{ docker_image_path }}"
  args:
    chdir: "{{ docker_compose_path }}"

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_repo }}
  no_log: true
