---

# Création du docker-compose.yml et démarrage des containers
- name: "Creating new docker-compose file"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    mode: 0755

- name: "Start docker-compose"
  command: docker-compose up -d
  args:
    chdir: "{{ docker_compose_path }}"
