export enum SectorPleasureType {
  PLEASURE_MARKET = 'PLEASURE_MARKET',
  SEA_DRIVING_LESSON = 'SEA_DRIVING_LESSON',
  OTHERS = 'OTHERS'
}

export enum SectorFishingType {
  GMS = 'GMS',
  RESTAURANT = 'RESTAURANT',
  MOBILE_FISHMONGER = 'MOBILE_FISHMONGER',
  SEDENTARY_FISHMONGER = 'SEDENTARY_FISHMONGER',
  FISH_AUCTION = 'FISH_AUCTION',
  FISHMONGER = 'FISHMONGER',
  LANDING_SITE = 'LANDING_SITE',
  OTHERS = 'OTHERS'
}

export type SectorEtablishmentType = SectorPleasureType | SectorFishingType
