include:
  - local: '.gitlab-ci/eco/dependency-check-template.yml'

dependency_check_node:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  extends: .dependency_check
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh
      --nvdDatafeed "${OWASP_CACHE_URL}" --nvdValidForHours 24
      --ossIndexUsername ${DEPENDENCY_CHECK_OSS_User} --ossIndexPassword ${DEPENDENCY_CHECK_OSS_Password}
      --data .dependency-checkdata/
      --project "${PROJECT_NAME} frontend ${PROJECT_VERSION}" --scan frontend/
      --enableExperimental --nodePackageSkipDevDependencies --nodeAuditSkipDevDependencies --failOnCVSS $FAIL_DP_CHECK_LVL --suppression .gitlab-ci/eco/suppression.xml
      --out syssi-ui-$PROJECT_VERSION-DP-check.html
  artifacts:
    when: always
    paths:
      - $PROJECT_NAME-frontend-$PROJECT_VERSION-DP-check.html
  tags:
    - selfservice
  needs:
    - job: build_projet_npm
  allow_failure: true

dependency_check_gradle:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  extends: .dependency_check
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh
      --nvdDatafeed "${OWASP_CACHE_URL}" --nvdValidForHours 24
      --ossIndexUsername ${DEPENDENCY_CHECK_OSS_User} --ossIndexPassword ${DEPENDENCY_CHECK_OSS_Password}
      --data .dependency-checkdata/
      --project "${PROJECT_NAME} api ${PROJECT_VERSION}" --scan backend/build/libs/rapportnav-${PROJECT_VERSION}.jar
      --disableNodeJS --disableNodeAudit --failOnCVSS $FAIL_DP_CHECK_LVL --suppression .gitlab-ci/eco/suppression.xml
      --out $PROJECT_NAME-backend-$PROJECT_VERSION-DP-check.html
  artifacts:
    when: always
    paths:
      - $PROJECT_NAME-backend-$PROJECT_VERSION-DP-check.html
  tags:
    - selfservice
  needs:
  - job: build_projet_gradle
  allow_failure: true