# TODO à adapter selon le projet
build_projet_npm:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  stage: build
  image: node:24
  script:
    - cd frontend
    - cp .env.example .env
    - npm ci --cache ${CI_PROJECT_DIR}/.npm
    - npm run build --verbose
  cache:
    key:
      prefix: "npm"
      files:
        - frontend/package-lock.json
    paths:
      - .npm/
    when: always
    policy: pull-push
  artifacts:
    name: "Npm artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 12 hours
    paths:
      - "frontend/dist"
  tags:
    - selfservice

test_projet_npm:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  stage: test
  image: node:24
  script:
    - cd frontend
    - cp .env.example .env
    - npm ci --cache ${CI_PROJECT_DIR}/.npm
    - npm run test:coverage
  cache:
    key:
      prefix: "npm"
      files:
        - frontend/package-lock.json
    paths:
      - .npm/
    when: always
    policy: pull
  artifacts:
    name: "Npm test artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 12 hours
    paths:
      - "frontend/coverage/lcov.info"
  tags:
    - selfservice
