# TODO à adapter selon le projet
build_projet_gradle:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  stage: build
  image: gradle:9.5.0-jdk25
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport
    - ./gradlew clean assemble
  artifacts:
    name: "Gradle artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: on_success
    paths:
      - "backend/build/libs/rapportnav-${PROJECT_VERSION}.jar"
      - "backend/build/reports/jacoco/"
  tags:
    - selfservice
