test_e2e:
  rules:
    - if: '$ENV_DEPLOIEMENT == "ecole" || $ENV_DEPLOIEMENT == "integration"'
      when: always
  stage: test
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  allow_failure: true
  variables:
    CI: 'true'
  script:
    - cd frontend
    - cp .env.example .env
    - npm ci --cache ${CI_PROJECT_DIR}/.npm
    - npx playwright test --config e2e/playwright.config.ts
  cache:
    key:
      prefix: npm
      files:
        - frontend/package-lock.json
    paths:
      - .npm/
    when: always
    policy: pull
  artifacts:
    name: 'E2E test results from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG'
    expire_in: 12 hours
    when: always
    paths:
      - frontend/playwright-report/
      - frontend/test-results/
    reports:
      junit: frontend/e2e-results.xml
  tags:
    - selfservice
