name: "[Build & Test] Backend"

on:
  #  push:
  #    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am every night

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
          cache-dependency-path: | # optional
            backend/*.gradle*
            backend/**/gradle-wrapper.properties

      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: wrapper

      - name: Print JAVA_HOME
        run: |
          echo "JAVA_HOME is $JAVA_HOME"

      - name: build
        run: make back-build

      - name: test
        run: make back-test

      - name: dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        env:
          JAVA_HOME: /opt/hostedtoolcache
        with:
          project: 'rapportnav'
          path: './backend'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports

      #      - name: "Analyse dependencies"
      #        run: make back-check-dependencies

      #      - name: "Tests"
      #        env:
      #          CI: true
      #        run: make back-test

      #      - name: "Check clean architecture"
      #        run: make check-clean-archi

#      - name: "Build"
#        run: make back-build-mvn
