name: "[Build & Test] Backend"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am every night

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Print JAVA_HOME
        run: |
          echo "JAVA_HOME is $JAVA_HOME"
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: cd backend
        run: cd backend

      - uses: gradle/gradle-build-action@v2.9.0
        id: setup-gradle
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          add-job-summary-as-pr-comment: on-failure

      - name: build and test
        run: make back-build

      #      - name: dependency-check
      #        uses: dependency-check/Dependency-Check_Action@main
      #        id: dependency-check
      #        env:
      #          JAVA_HOME: ${{ env.JAVA_HOME }}
      #        with:
      #          project: 'rapportnav'
      #          path: './backend'
      #          format: 'HTML'
      #          out: 'reports' # this is the default, no need to specify unless you wish to override it
      #          args: >
      #            --failOnCVSS 7
      #            --enableRetired

      #      - name: Upload Test results
      #        uses: actions/upload-artifact@master
      #        with:
      #          name: dependency-check-report
      #          path: ${{github.workspace}}/reports

      #      - name: "Analyse dependencies"
      #        run: make back-check-dependencies

      #      - name: "Tests"
      #        env:
      #          CI: true
      #        run: make back-test

      #      - name: "Check clean architecture"
      #        run: make check-clean-archi

      - name: "test maven"
        run: make back-test-mvn

      - name: "build maven"
        run: make back-build-mvn
