name: "[Build & Test] Frontend"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am every night

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install and Build Frontend
        uses: ./.github/actions/install-and-build-frontend

      - name: Analyse dependencies
        uses: oke-py/npm-audit-action@828ccb3b0710dfb351b6e9aaadec963c6953cacf
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: lwih
          issue_labels: vulnerability,test
          dedupe_issues: true
          working_directory: frontend

      - name: ESLint
        run: make front-lint

      - name: Tests & Coverage
        run: make front-coverage

      - name: Report Coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c
        with:
          working-directory: frontend

