name: Build and Test

on:
  push:
    branches: ["CHANGEME"]
  pull_request:
    branches: ["CHANGEME"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "[FRONTEND] Setup Node.js environment"
        uses: actions/setup-node@v3.8.0
        with:
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
          node-version: 18

      - name: "[FRONTEND] Install dependencies"
        run: make front-ci

      - name: "[FRONTEND] Analyse dependencies"
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: lwih
          issue_labels: vulnerability,test
          dedupe_issues: true
          working_directory: frontend

      - name: "[FRONTEND] Tests"
        run: make front-test

      - name: "[FRONTEND] Build"
        run: make front-build

      - name: "[BACKEND] Setup Java JDK"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
          java-package: jdk # optional (jdk or jre) - defaults to jdk

      - name: "[BACKEND] Analyse dependencies"
        run: make back-check-dependencies

      - name: "[BACKEND] Check clean architecture"
        run: make check-clean-archi

      - name: "[BACKEND] Build"
        run: make back-build-mvn
