name: "Release"

on:
  push:
    branches: ["CHANGEME"]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: set env VERSION
        id: version
        # run: export VERSION=${{ steps.extract_tag.outputs.tag }}
        run: export VERSION=0.0.0.16

      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2.git
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab-sml.din.developpement-durable.gouv.fr"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
          GITLAB_PROJECT_ID: "num3-exploitation/deploiement-continu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
