name: "Release"

on:
  push:
    branches: ["CHANGEME"]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: set env VERSION
        id: version
        # run: export VERSION=${{ steps.extract_tag.outputs.tag }}
        run: export VERSION=0.0.0.15

      # - name: Mirror + trigger CI
      #   uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      #   with:
      #     args: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2.git
      #   env:
      #     FOLLOW_TAGS: "false"
      #     FORCE_PUSH: "false"
      #     GITLAB_HOSTNAME: "gitlab-sml.din.developpement-durable.gouv.fr"
      #     # GITLAB_USERNAME: "svboxel"
      #     GITLAB_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
      #     GITLAB_PROJECT_ID: num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ github.actor }}
          url: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2.git
          # url: ${{ secrets.GITLAB_URL }}
          # username: ${{ secrets.GITLAB_USERNAME }}
          # Personal access token from gitlab.com
          token: ${{ secrets.GITLAB_MIRROR_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v4
        env:
          GITHUB_SHA: ${{ github.sha }}
          VERSION: 0.0.0.15
          # VERSION: ${{ steps.extract_tag.outputs.tag }}
          ENV_PROFILE: "prod"
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: infra/docker/app/Dockerfile
          push: true
          tags: |
            ghcr.io/mtes-mct/rapportnav2/rapportnav-app:${{ env.VERSION }}
            ghcr.io/mtes-mct/rapportnav2/rapportnav-app:latest
          build-args: |
            VERSION=${{ env.VERSION }}
            ENV_PROFILE=${{ env.ENV_PROFILE }}
            GITHUB_SHA=${{ github.sha }}
