name: "Release"

on:
  # push:
  #   branches: ["main"]
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Tag Name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: set env VERSION
        id: version
        run: export VERSION=${{ steps.extract_tag.outputs.tag }}

      - name: Build Docker Image
        id: build-image
        run: |
          docker buildx build \
            --file infra/docker/app/Dockerfile \
            --tag rapportnav-app:${{ steps.extract_tag.outputs.tag }} \
            .

      - name: Upload image to artifacts
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: rapportnav-app:${{ steps.extract_tag.outputs.tag }}

      - name: Configure Docker Credentials
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image to GitHub Packages
        run: make docker-tag-app

      - name: Push Docker Image to GitHub Packages
        run: make docker-push-appdocker push ${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
