name: "Release"

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #      - name: Get frontend version
      #        uses: avides/actions-project-version-check@v1.4.0
      #        id: frontend_version
      #        with:
      #          token: ${{ secrets.GITHUB_TOKEN }}
      #          file-to-check: frontend/package.json
      #          only-return-version: true
      #
      #      - name: Upload Frontend sourcemaps
      #        uses: ./.github/actions/upload-sourcemaps
      #        with:
      #          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #          VERSION: ${{ steps.frontend_version.outputs.version }}


      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2.git
        env:
          FOLLOW_TAGS: true
          FORCE_PUSH: true
          GITLAB_HOSTNAME: "gitlab-sml.din.developpement-durable.gouv.fr"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
          GITLAB_PROJECT_ID: "num3-exploitation/deploiement-continu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




