name: "Release"

on:
  push:
    branches: ["main"]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: set env VERSION
        id: version
        # run: export VERSION=${{ steps.extract_tag.outputs.tag }}
        run: export VERSION=0.0.0.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v4
        env:
          GITHUB_SHA: ${{ github.sha }}
          VERSION: 0.0.0.7
          # VERSION: ${{ steps.extract_tag.outputs.tag }}
          ENV_PROFILE: "prod"
        with:
          context: .
          # load: true
          builder: ${{ steps.buildx.outputs.name }}
          file: infra/docker/app/Dockerfile
          push: true
          tags: ghcr.io/mtes-mct/rapportnav2/rapportnav-app:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ENV_PROFILE=${{ env.ENV_PROFILE }}
            GITHUB_SHA=${{ github.sha }}
