name: "Release"

on:
  push:
    branches: ["main"]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Tag Name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: set env VERSION
        id: version
        # run: export VERSION=${{ steps.extract_tag.outputs.tag }}
        run: export VERSION=0.0.0.1

      - name: Build Docker Image
        id: build-image
        env:
          GITHUB_SHA: ${{ github.sha }}
          VERSION: 0.0.0.1
          # VERSION: ${{ steps.extract_tag.outputs.tag }}
          ENV_PROFILE: "prod"
        # run: |
        # docker buildx build \
        #   --file infra/docker/app/Dockerfile \
        #   --tag rapportnav-app:${{ steps.extract_tag.outputs.tag }} \
        #   .
        run: make docker-build-app

      # - name: Upload image to artifacts
      #   uses: ishworkh/container-image-artifact-upload@v1.0.0
      #   with:
      #     # image: rapportnav-app:${{ steps.extract_tag.outputs.tag }}
      #     image: rapportnav-app:0.0.0.1

      - name: List Docker Images
        run: docker images

      - name: Configure Docker Credentials
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image to GitHub Packages
        run: make docker-tag-app
        env:
          GITHUB_SHA: ${{ github.sha }}
          VERSION: 0.0.0.1
          # VERSION: ${{ steps.extract_tag.outputs.tag }}
          ENV_PROFILE: "prod"

      - name: Push Docker Image to GitHub Packages
        # run: make docker-push-appdocker push ${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
        run: make docker-push-appdocker push ${{ github.repository }}:0.0.0.1
