name: "[Release] Mirror push to gitlab"

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get frontend version
        uses: avides/actions-project-version-check@v1.4.0
        id: frontend_version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: frontend/package.json
          only-return-version: true

      - name: Upload Frontend sourcemaps
        uses: ./.github/actions/upload-sourcemaps
        with:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION: ${{ steps.frontend_version.outputs.version }}

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://gitlab-sml.din.developpement-durable.gouv.fr/rapportnav-v2/rapportnav_v2.git
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
          GIT_PUSH_ARGS: "--tags --prune"
          PUSH_ALL_REFS: false
          DEBUG: true
