name: "Release"

on:
  #  push:
  #    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: backend version
        id: backend_version
        run: |
          version=$(make back-version)
          echo "Version: $version"
          echo "::set-output name=version::$version"

      - name: Upload Frontend sourcemaps
        uses: ./.github/actions/upload-sourcemaps
        with:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION: ${{ steps.backend_version.outputs.version }}

      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/rapportnav-v2/rapportnav-v2.git
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab-sml.din.developpement-durable.gouv.fr"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
          GITLAB_PROJECT_ID: "num3-exploitation/deploiement-continu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




