# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "[Analyse] Trivy"

on:
  #  push:
  #    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am every night

permissions:
  contents: read

jobs:
  build:
    permissions:
      packages: write
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Analyse
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy on OS
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          vuln-type: "os"
          output: "trivy-results-os.sarif"
          severity: "LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload Trivy OS scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-os.sarif"
          category: "trivy-os"

      - name: Run Trivy on libraries
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          vuln-type: "library"
          output: "trivy-results-libs.sarif"
          severity: "HIGH,CRITICAL"

      - name: Upload Trivy Library scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-libs.sarif"
          category: "trivy-libs"
