# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "[Analyse] Trivy on Postgres"

on:
  #  push:
  #    branches: [ "main" ]
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am every night

permissions:
  contents: read

jobs:
  build:
    permissions:
      packages: write
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy on Postgres image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "postgres:15.7-alpine"
          format: sarif
          output: "postgres-trivy-results.sarif"
          severity: "LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload Postgres Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "postgres-trivy-results.sarif"
